// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    FeatherTwitter: typeof import('~icons/feather/twitter')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    FooterEmbed: typeof import('./src/components/FooterEmbed.vue')['default']
    LaRssSquare: typeof import('~icons/la/rss-square')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    Post: typeof import('./src/components/Post.vue')['default']
    RiArticleLine: typeof import('~icons/ri/article-line')['default']
    RiBookmarkLine: typeof import('~icons/ri/bookmark-line')['default']
    RiLightbulbLine: typeof import('~icons/ri/lightbulb-line')['default']
    RiStickyNoteLine: typeof import('~icons/ri/sticky-note-line')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ToggleTheme: typeof import('./src/components/ToggleTheme.vue')['default']
    UilGithubAlt: typeof import('~icons/uil/github-alt')['default']
  }
}
